In [3]:
from datasets import load_dataset

dataset = load_dataset("wikipedia", "20220301.simple")

In [5]:
from pprint import pprint

In [6]:
pprint((dataset))

DatasetDict({
    train: Dataset({
        features: ['id', 'url', 'title', 'text'],
        num_rows: 205328
    })
})


In [2]:

dataset = WikipediaDataset()

[nltk_data] Downloading package punkt to /home/ruslan/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
/home/ruslan/Desktop/My/Projects/.venv/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [5]:
pprint((dataset[0]))

(tensor([16784,   318,   262,  5544,  1227,   286,   262,   614,   287,   262,
        18322,   290,  8547, 22618, 50215,    11,   290,  2058,  1022,  2805,
          290,  1737,    13,   632,   318,   530,   286,  1440,  1933]),
 tensor([  318,   262,  5544,  1227,   286,   262,   614,   287,   262, 18322,
          290,  8547, 22618, 50215,    11,   290,  2058,  1022,  2805,   290,
         1737,    13,   632,   318,   530,   286,  1440,  1933,   284]),
 tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True]))


In [91]:
import torch
from decoder_models import TransformerDecoder
import torch.nn as nn
from tqdm import tqdm
import numpy as np


In [10]:

import WIKI_dataset
from torch.utils.data import DataLoader
from importlib import reload
reload(WIKI_dataset)
from WIKI_dataset import WikipediaDataset, CustomDataset

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
(train_data, test_data), tokenizer, VOCAB_SIZE = WikipediaDataset()
D_MODEL = 512
N_HEADS = 8
N_BLOCKS = 3
model = TransformerDecoder(VOCAB_SIZE, D_MODEL, N_HEADS, N_BLOCKS).to(DEVICE)
train_dataset = CustomDataset(train_data, tokenizer)
test_dataset = CustomDataset(test_data, tokenizer)
train_loader = DataLoader(train_dataset, batch_size=64, shuffle = True)
test_loader = DataLoader(test_dataset, batch_size=64, shuffle = False)

[nltk_data] Downloading package punkt to /home/ruslan/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
/home/ruslan/Desktop/My/Projects/.venv/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [10]:
print(smth)

In [11]:
loss_fnc = nn.CrossEntropyLoss()
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3)

In [12]:
model.train()
loss_epochs = []
for epoch in tqdm(range(20)):
    loss_epoch = []
    for input_ids, labels_ids, data_attention_mask in tqdm(train_loader):
        input_ids = input_ids.to(DEVICE)
        labels_ids = labels_ids.to(DEVICE)
        # pad_mask = pad_mask.to(DEVICE)
        data_attention_mask = data_attention_mask.to(DEVICE)

        preds = model(input_ids)
        preds = preds[data_attention_mask]
        labels_ids = labels_ids[data_attention_mask]

        optimizer.zero_grad()
        loss = loss_fnc(preds, labels_ids)
        loss.backward()
        optimizer.step()
        loss_epoch.append(loss.item())

    print(f'Loss_epoch {epoch + 1}: {np.mean(loss_epoch)}')
    loss_epochs.append(np.mean(loss_epoch))

  0%|          | 0/20 [01:21<?, ?it/s]


KeyboardInterrupt: 

In [13]:
torch.save(model.state_dict(), './model.pt')

In [145]:
from pprint import pprint

In [147]:
model_dict = torch.load('model_long_data.pt')

/tmp/ipykernel_12539/1708013745.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model_dict = torch.load('model_long_data.pt')


In [149]:
pprint(model_dict.keys())

odict_keys(['embedding.weight', 'pos.pe', 'blocks.0.layer_norm_1.weight', 'blocks.0.layer_norm_1.bias', 'blocks.0.layer_norm_2.weight', 'blocks.0.layer_norm_2.bias', 'blocks.0.MHA.query.weight', 'blocks.0.MHA.query.bias', 'blocks.0.MHA.key.weight', 'blocks.0.MHA.key.bias', 'blocks.0.MHA.value.weight', 'blocks.0.MHA.value.bias', 'blocks.0.MHA.out.weight', 'blocks.0.MHA.out.bias', 'blocks.0.MLP.0.weight', 'blocks.0.MLP.0.bias', 'blocks.0.MLP.2.weight', 'blocks.0.MLP.2.bias', 'blocks.1.layer_norm_1.weight', 'blocks.1.layer_norm_1.bias', 'blocks.1.layer_norm_2.weight', 'blocks.1.layer_norm_2.bias', 'blocks.1.MHA.query.weight', 'blocks.1.MHA.query.bias', 'blocks.1.MHA.key.weight', 'blocks.1.MHA.key.bias', 'blocks.1.MHA.value.weight', 'blocks.1.MHA.value.bias', 'blocks.1.MHA.out.weight', 'blocks.1.MHA.out.bias', 'blocks.1.MLP.0.weight', 'blocks.1.MLP.0.bias', 'blocks.1.MLP.2.weight', 'blocks.1.MLP.2.bias', 'blocks.2.layer_norm_1.weight', 'blocks.2.layer_norm_1.bias', 'blocks.2.layer_norm_2.w

In [92]:

model = TransformerDecoder(VOCAB_SIZE, D_MODEL, N_HEADS, N_BLOCKS)
model.load_state_dict(torch.load('model_alotofparameters.pt'))  # Загружаем состояние
model.to(DEVICE)

NameError: name 'VOCAB_SIZE' is not defined

In [106]:

@torch.no_grad()
def generate_batch(model, ids, is_decode = False, max_length = 20):

    model.eval()

    if not isinstance(ids, torch.Tensor):
        ids =  torch.tensor(ids, device = DEVICE)
        
    if ids.shape:
        # symbols = torch.tensor(ids, device = DEVICE).view(len(ids),1)
        symbols = ids.clone().detach().to(DEVICE).view(1,len(ids))

    else:
        # symbols = torch.tensor(ids, device = DEVICE).view(1,1)
        symbols = ids.clone().detach().to(DEVICE).view(1,1)

    for _ in range(max_length - 1):
        cur_symbols = model(symbols).argmax(-1)[:, -1][:, None]
        symbols = torch.cat([symbols, cur_symbols], dim = 1)
    if is_decode:
        symbols = tokenizer.batch_decode(symbols, skip_special_tokens=True)
    return symbols

In [39]:
input_ids, labels_ids, data_attention_mask = train_dataset[165]
text = tokenizer.decode(input_ids, skip_special_tokens=True)
start = 0
end = 5
print(text)
print(tokenizer.decode(input_ids[start:end], skip_special_tokens=False))
generate_batch(model, ids = input_ids[start:end], is_decode=True, max_length= 30)

NameError: name 'train_dataset' is not defined

In [135]:
def tokenize(data, max_length=30):
    data_tokens = tokenizer(data, return_tensors = 'pt', max_length = max_length, truncation=True)

    data_input_ids = data_tokens['input_ids'][0]

    return data_input_ids

In [142]:
text = "I am what"
input_ids = tokenize(text)
print(input_ids)
print(text)
generate_batch(model, ids = input_ids, is_decode=True, max_length= 30)

tensor([ 40, 716, 644])
I am what


['I am what is a term in the way a group of people who live in the same area as a general term. It is a common term in the suffix']

In [1]:
from importlib import reload
import prediction_model

In [83]:
reload(prediction_model)
from prediction_model import PredictionModel
model = PredictionModel('model_long_data.pt', 3)

In [80]:
"panda is a dangerous     ".rstrip(' ')

'panda is a dangerous'

In [86]:
print(model("panda is a dangerous      "))

panda is a dangerous
panda is a dangerous chemical compound.
 chemical compound.


In [60]:
import re

def count_words(text):
    # Используем регулярное выражение для поиска слов
    words = re.findall(r'\b\w+[\'.,!?"-]?\w*\b', text)
    return len(words)

# Пример использования
text = "Это пример текста.\nЗдесь есть переносы строк, и знаки препинания!"
word_count = count_words(text)
print(f"Количество слов: {word_count}")

Количество слов: 11
